services:
  web:
    container_name: web_camagru
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app # Maps your local project to the container
      - /usr/src/app/node_modules # Avoids overwriting node_modules
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${POSTGRES_NAME}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
  db:
    container_name: db_camagru
    image: postgres:12
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      #- ./postgres_data: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck: #making sure it starts up before the web service
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    #restart: always